export enum ActionTypes {
  CHANGE_PAGE = "CHANGE_PAGE",

  ADD_TO_CART = "ADD_TO_CART",
  REMOVE_FROM_CART = "REMOVE_FROM_CART",
  CHANGE_FULLNAME = "CHANGE_FULLNAME",
  CHANGE_MOBILE = "CHANGE_MOBILE",
  CHANGE_ADDRESS = "CHANGE_ADDRESS",
  CHANGE_TIME = "CHANGE_TIME",
  CHANGE_LOCATION = "CHANGE_LOCATION",
  LOAD_USER_INFO = "LOAD_USER_INFO"
}
