export enum ActionTypes {
  CHANGE_PAGE = "CHANGE_PAGE",
  CHANGE_TAB_ID = "CHANGE_TAB_ID",

  ADD_TO_CART = "ADD_TO_CART",
  REMOVE_FROM_CART = "REMOVE_FROM_CART",

  CHANGE_DELIVERKIND = "CHANGE_DELIVERKIND",
  CHANGE_DELIVERDISTRICT = "CHANGE_DELIVERDISTRICT",

  CHANGE_MOBILE = "CHANGE_MOBILE",
  CHANGE_FULLNAME = "CHANGE_FULLNAME",
  CHANGE_ADDRESS = "CHANGE_ADDRESS",

  CHANGE_DATE = "CHANGE_DATE",
  CHANGE_TIME = "CHANGE_TIME",

  // CHANGE_TIME = "CHANGE_TIME",

  // CHANGE_LOCATION = "CHANGE_LOCATION",

  TRY_LOADING_INIT = "TRY_LOADING_INIT",
  SUCCESS_LOAD_INIT = "SUCCESS_LOAD_INIT",
  FAILED_LOAD_INIT = "FAILED_LOAD_INIT",

  TRY_LOADING_USER_INFO = "TRY_LOADING_USER_INFO",
  SUCCESS_LOAD_USER_INFO = "SUCCESS_LOAD_USER_INFO",
  FAILED_LOAD_USER_INFO = "FAILED_LOAD_USER_INFO",

  TRY_LOADING_LOCATION = "TRY_LOADING_LOCATION",
  SUCCESS_LOAD_LOCATION = "SUCCESS_LOAD_LOCATION",
  FAILED_LOAD_LOCATION = "FAILED_LOAD_LOCATION",

  TRY_MAKING_ORDER = "TRY_MAKING_ORDER",
  SUCCESS_MAKE_ORDER = "SUCCESS_MAKE_ORDER",
  FAILED_MAKE_ORDER = "FAILED_MAKE_ORDER",

  TRY_LOADING_ORDER = "TRY_LOADING_ORDER",
  SUCCESS_LOAD_ORDER = "SUCCESS_LOAD_ORDER",
  FAILED_LOAD_ORDER = "FAILED_LOAD_ORDER"
}
